[workspace]
authors = ["Open Force Field Initiative <info@openforcefield.org>"]
channels = ["conda-forge"]
name = "fitlib"
platforms = [ "linux-64", "osx-arm64" ]

[tasks]
run_tests = "python -m pytest -n auto --cov=fitlib --cov-append --cov-report=xml --color=yes fitlib/tests/"
run_mypy = "python -m mypy fitlib/"
make_docs = "sphinx-build -b html docs docs/_build/html"
clean_docs = "rm -rf docs/_build docs/api/generated"

[dependencies]
python = ">=3.12"
setuptools-scm = ">=8"
pip = "*"
msgpack-python = "*"
pydantic = "*"
pydantic-units = "*"
openff-toolkit-base = "0.18.*"
openff-interchange-base = "0.5.*"
pytorch = "*"
pyarrow = "*"
datasets = "*"
scipy = "*"
rdkit = "*"
matplotlib-base = "*"
panel = "*"
python-symengine = "*"
jupyter = "*"
nbconvert = "*"
tensorboard = "*"
tensorboardx = "*"
uncertainties = "*"

[pypi-dependencies]
fitlib = { path = ".", editable = true }

[feature.cu12]
platforms = ["linux-64"]

[feature.cu12.system-requirements]
cuda = "12"

[feature.cu12.dependencies]
cuda-version = "12.*"
pytorch-gpu = "*"

[feature.mm.dependencies]
openmm = "*"
# packmol = "*"
rdkit = "*"
numpy = "*"
msgpack-python = "*"
nnpops = "*"
pydantic = "*"
pydantic-units = "*"

[feature.fe.dependencies]
mdtraj = "*"
absolv-base = "=1.0.4"
femto = "=0.2.1"  # API break in 0.3.x that absolv hasn't been updated for?

[feature.openeye]
channels = ["openeye"]

[feature.openeye.dependencies]
openeye-toolkits = "*"

[feature.ambertools.dependencies]
ambertools = "*"

[feature.examples.dependencies]
jupyter = "*"
nbconvert = "*"
nglview = "*"
smirnoff-plugins = "*"

[feature.dev.dependencies]
pre-commit = "*"
ruff = "*"
nbqa = "*"
ipython = "*"
ipdb = "*"

[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
pytest-xdist = "*"
codecov = "*"

[feature.docs.dependencies]
sphinx = ">=6.0,<7.0"
myst-nb = ">=1.0"
myst-parser = ">=2.0"
sphinx-notfound-page = "*"
sphinxcontrib-bibtex = ">=2.5"
ipython = "*"
libsass = "*"

[feature.docs.pypi-dependencies]
openff-sphinx-theme = { git = "https://github.com/openforcefield/openff-sphinx-theme.git" }

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[tool.pixi.feature.pydantic-2.dependencies]
pydantic = ">=2.0"

[tool.pixi.feature.pydantic-1.dependencies]
pydantic = "<2.0"

[feature.typing.pypi-dependencies]
mypy = "*"
scipy-stubs = "*"
types-tqdm = "*"
pandas-stubs = "*"

[environments]
# from smee, there were some environments without the "mm" feature
# "base" environments need something for pre-AshGC force fields, openeye is vastly easier to install
base-py312 = [ "py312", "openeye", "ambertools", "test", "typing" ]
base-py313 = [ "py313", "openeye", "ambertools", "test", "typing" ]
py312 = [ "py312", "mm", "fe", "test", "typing" ]
dev = [ "py312", "mm", "fe", "openeye", "test", "typing", "dev" ]
docs = [ "py312", "docs" ]
