[build-system]
requires = ["setuptools>=61.0", "setuptools_scm>=8" ]
build-backend = "setuptools.build_meta"

[project]
name = "fitlib"
description = "Fit force fields with PyTorch."
license = "MIT"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.12"
classifiers = ["Programming Language :: Python :: 3"]
[[project.authors]]
name = "Open Force Field Initiative"
email = "info@openforcefield.org"

[tool.setuptools.packages.find]
include = ["fitlib*"]

[tool.setuptools_scm]

[tool.ruff.lint]
ignore = ["C901","E402","E501"]
select = ["B","C","E","F", "I", "W","B9"]

[tool.coverage.run]
omit = ["**/_tests/*"]

[tool.coverage.report]
exclude_lines = [
    "@overload",
    "pragma: no cover",
    "raise NotImplementedError",
    "if __name__ = .__main__.:",
    "if TYPE_CHECKING:",
    "if typing.TYPE_CHECKING:",
]

[tool.mypy]
# fix me!
disable_error_code = [
    "misc",
    "call-arg",
    "attr-defined",
    "arg-type",
    "type-arg",
    "valid-type",
    "return-value",
    "assignment",
    "union-attr",
    "index",
    "var-annotated",
    "call-overload",
    "operator",
    "no-redef",
    "dict-item",
    "list-item",
]
mypy_path = "stubs/"
exclude = "fitlib/tests"
python_version = "3.12"
warn_unused_ignores = true
plugins = "pydantic.mypy"
warn_incomplete_stub = true
warn_unused_configs = true
show_error_codes = true
[[tool.mypy.overrides]]
module = [
  "absolv",
  "absolv.*",
  "datasets",
  "datasets.*",
  "openff.toolkit",
  "smirnoff_plugins.*",
  "openmm",
  "openmm.unit",
  "openmm.app",
  "pydantic_units",
  "pymbar",
  "pymbar.timeseries",
  "femto",
  "femto.*",
  "parmed",
  "parmed.*",
  "mdtraj",
  "NNPOps",
  "NNPOps.*",
  "symengine",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
markers = [
    "fe: run free energy regression tests",
]
addopts = "-m 'not fe'"
