[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=61", "setuptools-scm>=8" ]

[project]
name = "fitlib"
description = "Fit force fields with PyTorch."
readme = "README.md"
license = "MIT"
authors = [
  { name = "Open Force Field Initiative", email = "info@openforcefield.org" },
]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [ "version" ]

[tool.setuptools]
packages.find.include = [ "fitlib*" ]

[tool.setuptools_scm]

[tool.ruff]
lint.select = [ "B", "B9", "C", "E", "F", "I", "W" ]
lint.ignore = [ "C901", "E402", "E501" ]

[tool.mypy]
mypy_path = "stubs/"
exclude = "fitlib/_tests"
python_version = "3.12"
warn_unused_ignores = true
# fix me!
disable_error_code = [
  "arg-type",
  "assignment",
  "attr-defined",
  "call-arg",
  "call-overload",
  "dict-item",
  "index",
  "list-item",
  "misc",
  "no-redef",
  "operator",
  "return-value",
  "type-arg",
  "union-attr",
  "valid-type",
  "var-annotated",
]
plugins = "pydantic.mypy"
warn_incomplete_stub = true
warn_unused_configs = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
  "datasets",
  "datasets.*",
  "femto",
  "femto.*",
  "mdtraj",
  "NNPOps",
  "NNPOps.*",
  "openff.toolkit",
  "openmm",
  "openmm.app",
  "openmm.unit",
  "parmed",
  "parmed.*",
  "pydantic_units",
  "pymbar",
  "pymbar.timeseries",
  "smirnoff_plugins.*",
  "symengine",
]
ignore_missing_imports = true

[tool.pytest]
ini_options.addopts = "-m 'not fe'"
ini_options.markers = [ "fe: run free energy regression tests" ]

[tool.coverage]
run.omit = [ "**/_tests/*" ]
report.exclude_lines = [
  "@overload",
  "if __name__ = .__main__.:",
  "if TYPE_CHECKING:",
  "if typing.TYPE_CHECKING:",
  "pragma: no cover",
  "raise NotImplementedError",
]
